### ISSUE TITLE
Open the project creation with template id passed with `meraki://:templateId`

### ISSUE THREAD

**Issue by marcopiraccini** [platformatic/meraki#150]
Depends on: https://github.com/platformatic/meraki/issues/149

If a `templateId` is specified:
- Start the app as usual, with a label on the first screen that show the template name [needs design] 
- Pre-select the template in the select template screen

NOTE:
- We need to check if the template is actually visible to the user

**Comment by Fmusso94** [comment]
@marcopiraccini as discussed, here is a possible UX/UI Solution showing the label and the Template name that will be added to the Application. The design is on Figma

![Screenshot 2024-01-23 at 10 54 29 AM](https://github.com/platformatic/meraki/assets/78840283/42ea506b-5063-439b-af6f-c69f119fec11)

As usual, once the fields "Application name" and "Destination folder" are filled, users can click next and proceed to the next step, but in this case, the template has already been added.

CC: @tonysnowboardunderthebridge
