### ISSUE TITLE
Show the login status

### ISSUE THREAD

**Issue by marcopiraccini** [platformatic/meraki#151]
User can login using `platformatic login` (and MUST login to see all the private stackables). 
Meraki must show this status so the user can understand this
Check if deisgn is already done.

**Comment by Fmusso94** [comment]
@marcopiraccini the design is on Figma. With Luca, we identified 3 user states:
- Offline:
![Screenshot 2024-01-23 at 8 32 49 AM](https://github.com/platformatic/meraki/assets/78840283/b0efef5d-f4a0-4708-98b4-3a12260b76df)

- Log Session Expired:
![Screenshot 2024-01-23 at 8 33 33 AM](https://github.com/platformatic/meraki/assets/78840283/a7ba837e-81ce-46ab-9d27-22f438419ce8)

- Online: 
![Screenshot 2024-01-23 at 8 34 12 AM](https://github.com/platformatic/meraki/assets/78840283/a1c71f3c-0659-4354-9ef7-04deecfef3e2)

For both "Offline" and "Log Session Expired" statuses, we might need to disable the Organization field. Also, for those statuses, we also need to discuss if the button "platformatic login" is clickable, if yes decide the outcome.

CC: @tonysnowboardunderthebridge

**Comment by marcopiraccini** [comment]
On this, @tonysnowboardunderthebridge we will define an `checkLogin` API on main returning a status: `OK, EXPIRED, INVALID`.
About "invalid" @Fmusso94 this will really mean that there is no auth token, so we might use another label to express that login hasn't been done.
