### ISSUE TITLE
Change template and plugin details, taking not the array but the payload

### ISSUE THREAD

**Issue by tonysnowboardunderthebridge** [platformatic/meraki#159]

**Comment by ivan-tymoshenko** [comment]
@tonysnowboardunderthebridge I cannot find the place in meraki where it uses `/package-manager/stackables/available/${id}` request. Maybe you can point me.

**Comment by tonysnowboardunderthebridge** [comment]
@ivan-tymoshenko my fault, I forget that on meraki we don't call the api for single endpoint but we will send the props directly to the template/plugin detail.
