### ISSUE TITLE
The "use plugin" button is not shown by default on Mac OS X (a user has to scroll)

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#171]
<img width="1511" alt="Screenshot 2024-01-24 at 17 38 35" src="https://github.com/platformatic/meraki/assets/52195/a93e7ba9-9180-4e75-b554-882f58be0576">

**Comment by Fmusso94** [comment]
@tonysnowboardunderthebridge I am testing this and I can actually see the button WITHOUT scrolling. I am testing the smallest and the largest view possible and both scenarios are showing the button as aspected. So please test it as well when you have a minute.
