### ISSUE TITLE
The scrollbar with multiple service "cut" relevant information. (no page level scrollbars)

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#172]
<img width="1512" alt="Screenshot 2024-01-24 at 17 39 07" src="https://github.com/platformatic/meraki/assets/52195/8ca65c67-ae57-4cce-9f0b-20a42a3da62f">

**Comment by Fmusso94** [comment]
Hey @tonysnowboardunderthebridge as you were saying on Slack we shouldn't have any vertical scroll bar the height should be fixed. In this scenario, Matteo reported the issue where without scrolling down is impossible to see the buttons "Back" and "Next - Prepare Folder". Please prioritize this fix
