### ISSUE TITLE
Runtime: Visualisation of services and dependencies

### ISSUE THREAD

**Issue by simonplend** [platformatic/meraki#176]
Holding a mental model of what services exist and the dependencies between them is quite difficult - it would be great if this could be visualised in a web UI:

- Runtime application - services that it contains, what the entrypoint is
- Composer service - APIs that it aggregates
- Client dependencies - services that other services depend on via a Platformatic client

**Comment by marcopiraccini** [comment]
We actullay did this, except the "client dependencies" which needs more analysis.
