### ISSUE TITLE
Add Last Update on Plugins and Template Details (Dedicated component)

### ISSUE THREAD

**Issue by tonysnowboardunderthebridge** [platformatic/meraki#180]
As described

cc @marcopiraccini @Fmusso94

**Comment by Fmusso94** [comment]
Thank you @tonysnowboardunderthebridge the design is on Figma. Here is a preview of it:
![Screenshot 2024-01-26 at 10 53 48 AM](https://github.com/platformatic/stackables-marketplace/assets/78840283/6c51ede6-2cef-4f90-9b36-59f5b2901a7d)
