### ISSUE TITLE
Meraki Review - Notion Page

### ISSUE THREAD

**Issue by tonysnowboardunderthebridge** [platformatic/meraki#251]
here the list of bugs
https://www.notion.so/platformatic/Meraki-Review-fdb91c79711c499f91150371eeaf2428

**Comment by marcopiraccini** [comment]
Can we close this now @tonysnowboardunderthebridge ?

**Comment by tonysnowboardunderthebridge** [comment]
@marcopiraccini I need to double check the remaining points on notion page

**Comment by marcopiraccini** [comment]
Please do, and if there are remaining stuff, please open a separate issue. Otherwise is not clear what is left and the priority of what is left

**Comment by tonysnowboardunderthebridge** [comment]
I'll close it and open a new issue with the remaining stuff
