### ISSUE TITLE
Memory Leak React - prevent with AbortController

### ISSUE THREAD

**Issue by tonysnowboardunderthebridge** [platformatic/meraki#26]
Let's implement this to prevent memory leak
https://medium.com/geekculture/avoid-memory-leaks-in-your-react-app-by-canceling-api-calls-9cf692c06573
 useEffect(() => {
    setLoading(true);
    const controller = new AbortController();
    fetch("http://localhost:3001/posts", { signal: controller.signal })
      .then(response => response.json())
      .then(json => {
        setPosts(json);
        setLoading(false);
      })
      .catch(error => {
        window.alert(error);
        setLoading(false);
      });
    return () => {
      controller.abort();
    };
  }, []);

**Comment by marcopiraccini** [comment]
Is this done @tonysnowboardunderthebridge ?

**Comment by tonysnowboardunderthebridge** [comment]
Unfortunately No!

**Comment by tonysnowboardunderthebridge** [comment]
this here make no sense, I will close it and open on stackables marketplace (there it have more sense)
