### ISSUE TITLE
Improve Service plugin UI

### ISSUE THREAD

**Issue by leorossi** [platformatic/meraki#386]
I am editing a runtime app and I wanted to remove one of the plugins, but I can't see the relevant part of the name (see screenshot)

![Screenshot 2024-03-19 at 17 22 54](https://github.com/platformatic/meraki/assets/604220/334ca602-3710-4cf0-98b1-102933e4aa1b)

If I keep the mouse on the plugin name I can see the full name but after few seconds, which is not a great experience.

I suggest an instant popup when the name doesn't fit the space

**Comment by marcopiraccini** [comment]
This is still actual @leorossi ?

**Comment by leorossi** [comment]
Yes, with current `main` (dd1030f86c4c31557e49f9a6ff219a14eea526b3) the system popup does not even appear anymore

**Comment by tonysnowboardunderthebridge** [comment]
Resolved with https://github.com/platformatic/meraki/pull/547
