### ISSUE TITLE
Metrics with switched off runtime

### ISSUE THREAD

**Issue by marcopiraccini** [platformatic/meraki#393]
If a runtime is off, metrics cannot been collected (and currently meraki is not storing metrics) so there is no sense to show metrics. 
We need to decided what to do if an application is not running (disable button? show a message when clicking on metrics?) and implement it. 
If we show a message, the metric page itself should check if the application is running.

**Comment by tonysnowboardunderthebridge** [comment]
On Figma there is this title to show

![Image](https://github.com/platformatic/meraki/assets/25035977/a90b982f-930f-4ea8-b43b-9d3705bf6a8b)
