### ISSUE TITLE
Get the status of the app even in the detail correctly

### ISSUE THREAD

**Issue by marcopiraccini** [platformatic/meraki#409]
If we start the app from the lis, then we switch quickly to the detail, the app is still "stopped" even if running. 
We should actually push the status of the app generating an event from the `main` thread to the `render` thread.

**Comment by tonysnowboardunderthebridge** [comment]
Not Done yet.
change on store applicationStatus and setApplicaitionStatus to handle like (not only a string)
{
'idApp1': status,
'idApp2': status...
}

**Comment by tonysnowboardunderthebridge** [comment]
Done with https://github.com/platformatic/meraki/pull/453
