### ISSUE TITLE
Support "reopening" a project

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#42]
Something that would be extremely nice is to "reopen" a project and add a new service there.

This is currently _not_ supported by our App, but it should be added post-launch.

**Comment by marcopiraccini** [comment]
Depends on #226

**Comment by tonysnowboardunderthebridge** [comment]
Hi @mcollina @marcopiraccini 
this is done with the import app https://github.com/platformatic/meraki/issues/272
