### ISSUE TITLE
we require the app the be started to access the logs

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#471]
In case the app is not started, we have a message saying to "click here to load previous logs", however we need to start the app to load them.

I think we should change the message.

**Comment by tonysnowboardunderthebridge** [comment]
Application Stopped

<img width="1728" alt="Schermata 2024-03-27 alle 11 03 12" src="https://github.com/platformatic/meraki/assets/25035977/b36c58b6-e938-4e4a-bafd-d3f076fa1c4b">

Application Started
<img width="1728" alt="Schermata 2024-03-27 alle 11 04 27" src="https://github.com/platformatic/meraki/assets/25035977/46a6cd48-076e-4711-ba1b-c35d37dea084">
