### ISSUE TITLE
ee leak

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#476]
```
(node:86511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 app-logs listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `Electron Helper (Renderer) --trace-warnings ...` to show where the warning was created)
```

**Comment by marcopiraccini** [comment]
@tonysnowboardunderthebridge I think we forgot some `useEffect` cleanups. 
see: https://stackoverflow.com/questions/73408804/electron-react-maxlistenersexceededwarning-possible-eventemitter-memory-leak-d 

Can you please check?
