### ISSUE TITLE
Meraki Review - Fixes after tests

### ISSUE THREAD

**Issue by tonysnowboardunderthebridge** [platformatic/meraki#532]
## Meraki - Compose App (Multi-Plugins)

![Screenshot 2024-01-24 at 8 20 35 AM](https://github.com/platformatic/meraki/assets/25035977/ddf77e36-148e-416c-860e-d92e03bbb581)

- B) **🟢** The plugin name should be white 100%. It also should be clickable and open the Plugin Detail view DONE ✅ 
- C) **🟠** When we remove a plugin the animation is weird we can improve it.

<img width="718" alt="Schermata 2024-04-03 alle 11 18 37" src="https://github.com/platformatic/meraki/assets/25035977/e1e4dd57-c4f2-49cd-b77b-953aafbe9ce0">

Meraki - Expanded Plugin View (Service with 5+ plugins)
D) 🟢 We need some padding (4px) between the cards and the scroll bar

<img width="727" alt="Schermata 2024-04-03 alle 11 21 19" src="https://github.com/platformatic/meraki/assets/25035977/59fd2bfd-35b5-42ff-b309-8e9355a23842">

<img width="719" alt="Schermata 2024-04-03 alle 11 21 37" src="https://github.com/platformatic/meraki/assets/25035977/8d88561c-3678-4d44-9cf9-ff9ee9835a43">

<img width="743" alt="Schermata 2024-04-03 alle 11 22 04" src="https://github.com/platformatic/meraki/assets/25035977/9b1e5b91-7a3e-48e4-9684-1250e0cb4259">

<img width="732" alt="Schermata 2024-04-03 alle 11 22 29" src="https://github.com/platformatic/meraki/assets/25035977/c27e5633-ae02-40cc-8c38-77de3c04fad2">

<img width="730" alt="Schermata 2024-04-03 alle 11 23 24" src="https://github.com/platformatic/meraki/assets/25035977/1b1089e4-0b00-4426-8297-116284388a94">

**Comment by tonysnowboardunderthebridge** [comment]
<img width="739" alt="Schermata 2024-04-03 alle 11 25 25" src="https://github.com/platformatic/meraki/assets/25035977/e1f13129-8076-49d4-b605-5e4d2125af52">

**Comment by marcopiraccini** [comment]
One of the points also solves https://github.com/platformatic/meraki/issues/386
