### ISSUE TITLE
Add a button to update Platformatic

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#553]

**Comment by marcopiraccini** [comment]
@Fmusso94 can you provide the design part?

**Comment by Fmusso94** [comment]
We should go for the following solution:

![Screenshot 2024-04-05 at 7 08 14 AM](https://github.com/platformatic/meraki/assets/78840283/8deeac8f-4357-4e9d-be39-81122131aff9).

@marcopiraccini @mcollina

**Comment by Fmusso94** [comment]
@marcopiraccini In the application lists, Recents and All, I would suggest adding a tooltip when hovering over the alert icon that shows the same message. As a user, I wonder what is the alert about the version, and I would expect to see an explanation message. I suggest the following solution:

![Screenshot 2024-04-08 at 10 05 49 AM](https://github.com/platformatic/meraki/assets/78840283/3847941d-9c3e-44d0-bd61-885bf8c24374)
