### ISSUE TITLE
how to unstuck the application on first start?

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#691]
<img width="1323" alt="Screenshot 2024-05-11 at 09 32 37" src="https://github.com/platformatic/meraki/assets/52195/d4f76ebe-a8c2-4cfc-96ab-3272dd627c49">

My application got stuck at startup (I'm on a flaky internet connection)

**Comment by marcopiraccini** [comment]
I think this happens because the spinner is removed when the `satrtRuntime` succeed. 
But we need to be sure we exit from this:
- In case of errors
- After a log timeot (60 seconds?)

@tonysnowboardunderthebridge can you please verify this?

**Comment by tonysnowboardunderthebridge** [comment]
@marcopiraccini @mcollina error not handled on getApplication

here the quick fix to at least show something https://github.com/platformatic/meraki/pull/692
