### ISSUE TITLE
Do not generate routes and tests by default

### ISSUE THREAD

**Issue by marcopiraccini** [platformatic/meraki#706]
Meraki should follow the defaults set by the satckable about plugin/test generation. 

The point to change is: https://github.com/platformatic/meraki/blob/main/src/main/generate.mjs#L141

**Comment by mcollina** [comment]
This is not exactly correct, in the sense that it should be up to the stackable to decide if they want plugins and tests by default, not imposed from above.

**Comment by marcopiraccini** [comment]
@mcollina actually, agree. 
So Meraki should not touch "plugin" and "test" here: https://github.com/platformatic/meraki/blob/main/src/main/generate.mjs#L141 

Renaming this issue accordingly
