### ISSUE TITLE
Meraki hangs forever if network is not available

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#77]

**Comment by marcopiraccini** [comment]
This is probably an error which is not catched by UI (ths clienttry to call the API and fails).  can you please check @tonysnowboardunderthebridge ?
In case of error we should show an error dialog

**Comment by tonysnowboardunderthebridge** [comment]
@mcollina @Fmusso94 where and how we can display an error in the app?

**Comment by marcopiraccini** [comment]
@tonysnowboardunderthebridge anything is better than hangs forever :) 
If the design is missing, mark with the "missing design" label, but imo for this case a simple and quick generic error dialog is fine. 
After all, this shouldn't happen.
